# Dockerfile para herramientas de desarrollo de Dictatux

FROM python:3.11-slim
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq && \
    apt-get install -y -qq \
        qt6-languageserver-dev \
        qt6-tools-dev-tools && \
    # Install PySide6 to get pyside6-rcc
    pip install --no-cache-dir PySide6 && \
    # Linsk to get tools in the path PATH
    ln -s /usr/lib/qt6/bin/lupdate /usr/bin/lupdate && \
    ln -s /usr/lib/qt6/bin/lrelease /usr/bin/lrelease && \
    ln -s /usr/local/bin/pyside6-rcc /usr/bin/pyrcc6 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

# Herramientas disponibles:
# - lupdate: Extraer cadenas traducibles a archivos .ts
# - lrelease: Compilar archivos .ts a .qm
# - pyrcc6: Compilar recursos Qt (.qrc) a archivos Python
